### ISSUE TITLE
Implement the play state

### ISSUE THREAD

**Issue by WilliamHLe** [WilliamHLe/star-battle-ntnu#16]
- [x] Implement the view (@Shirajuki)
- [x] Create health component (@TorbsT) 
- [x] Create system for UFO (@Shirajuki ) 
- [x] Create system for health (@macmikke) - #43 
- [x] Create system for trajectory (@kavusiks) - #41 
- [x] Create entity factory (@Shirajuki)

**Comment by Shirajuki** [comment]
This issue is more or less done.
Just need to merge #43 and #44 :)
